spring:
    application: 
        name: rfp
    output:
        ansi:
            enabled: always
    datasource:
        url: jdbc:mysql://localhost:3306/rfp
        username: root
        password: root
    # jpa:
    #     hibernate:
    #         ddl-auto: create-drop
    